{% set name = "aes-stream-drivers" %}
{% set version = "5.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: f649de81143b8afe3c1c148aa6b2949357d719737aae0b0443500af4d8fd99cd

build:
  skip: True  # [win or osx]
  number: 0

about:
  home: https://jupp0r.github.io/prometheus-cpp
  license: MIT
  license_family: MIT
  summary: 'Headers for streaming kernel drivers (PGP, AxiStream, ExoTem) '
  description: |
    Development headers for streaming kernel drivers
  doc_url: https://github.com/slaclab/aes-stream-drivers
  dev_url: https://github.com/slaclab/aes-stream-drivers

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

